couchbase-init:
    build: .
    ports:
        - "8091:8091"
    environment:
        - CLUSTER_RAM_QUOTA=1024
    restart: always
    volumes:
        - ~/couchbase/node1:/opt/couchbase/var
couchbase:
    build: .
    links:
        - couchbase-init:couchbase
    environment: 
        - CLUSTER_RAM_QUOTA=1024
    restart: always
    
    