couchbase-init:
    build: .
    ports:
        - "8091:8091"
        - "8092:8092"
        - "8093:8093"
        - "11210:11210"
    environment:
        - CLUSTER_RAM_QUOTA=512
    restart: always
    volumes:
        - ~/couchbase/node1:/opt/couchbase/var
couchbase:
    build: .
    links:
        - couchbase-init:couchbase
    environment: 
        - CLUSTER_RAM_QUOTA=512
    restart: always
    
    
