couchbase-init:
    build: .
    ports:
        - "127.0.0.1:8091:8091"
        - "127.0.0.1:8092:8092"
        - "127.0.0.1:8093:8093"
        - "127.0.0.1:11210:11210"
    environment:
        - CLUSTER_RAM_QUOTA=1024
    restart: always
    volumes:
        - ~/couchbase/node1:/opt/couchbase/var
couchbase:
    build: .
    links:
        - couchbase-init:couchbase
    environment: 
        - CLUSTER_RAM_QUOTA=1024
    restart: always
    
    
